swagger: '2.0'
info:
  version: Platform.v2026.2.0.0.20260708
  title: Rest Activity CompliancePermissions API
  description: EMS Rest API
  contact:
    name: Cority
    email: support@cority.com
    url: https://cority.com
tags:
- name: CompliancePermissions
paths:
  /ver2/CompliancePermissionService.svc/locations/permissions/{locationId}:
    get:
      tags:
      - CompliancePermissions
      summary: Get Permissions per location
      description: "Get Permissions per location\n\n\nenvianceSdk.compliancePermission.getLocationPermission\r\n```\r\n[\r\n    \"324a63d8-35df-473f-b8d8-514872c7f70e\",\r\n    \"onsuccess\",\r\n    \"onerror\"\r\n]\r\n```\r\n\n"
      operationId: Enviance.RestServices.Ver2.ComplianceModel.Impl.CompliancePermissionService.GetLocationPermissions
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: EnvApi-Systemid
        in: header
        description: Specify specific system to run instead of Home
        type: string
      - name: EnvApi-Packageid
        in: header
        description: (optional) Clients application/package ID
        type: string
      - name: EnvApi-Udf-DateTime-Iso-In-CustomFields
        in: header
        description: Udfs of DateTime should use Iso
        type: string
        default: 'true'
      - name: EnvApi-Udf-DateTime-ReadInUserTz
        in: header
        description: (obsolete) Udfs of DateTime type whould be in ReadInUserTz
        type: string
      - name: EnvApi-Udf-Value-Invariant
        in: header
        description: (optional) Udfs - Force Non-Localized (invariant) values
        type: string
      - name: EnvApi-Localization-All
        in: header
        description: (optional) Extend objects with User-given Localizations
        type: string
      - name: x-client-request-id
        in: header
        description: (optional) Client ID for double submit prevention
        type: string
      - name: locationId
        in: path
        required: true
        type: string
      responses:
        default:
          description: not available
          schema:
            $ref: '#/definitions/Enviance.RestServices.Ver2.ComplianceModel.CompliancePermissionInfo'
definitions:
  Enviance.RestServices.Ver2.ComplianceModel.CompliancePermissionInfo:
    type: object
    format: Enviance.RestServices.Ver2.ComplianceModel.CompliancePermissionInfo
securityDefinitions:
  Basic:
    type: basic
    description: Forces authentication with credentials via an api gateway
  EnvianceAuth:
    type: apiKey
    description: "**Enviance \\<SessionId\\>**. \r\n\t\t\t\t\t  Obtain SessionId by POST /ver2/AuthenticationService.svc/sessions first"
    name: Authorization
    in: header
