swagger: '2.0'
info:
  version: Platform.v2026.2.0.0.20260708
  title: Rest Activity MaterialData API
  description: EMS Rest API
  contact:
    name: Cority
    email: support@cority.com
    url: https://cority.com
tags:
- name: MaterialData
paths:
  ? /ver2/MaterialDataService.svc/materialdata/{activityIdOrNameOrUniqueTag}/begin/{completeBegin}/end/{completeEnd}/{locationIdOrPathOrUniqueTag}
  : get:
      tags:
      - MaterialData
      operationId: Enviance.RestServices.Ver2.MaterialActivity.Data.Impl.MaterialDataService.GetMaterialData
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: EnvApi-Systemid
        in: header
        description: Specify specific system to run instead of Home
        type: string
      - name: EnvApi-Packageid
        in: header
        description: (optional) Clients application/package ID
        type: string
      - name: EnvApi-Udf-DateTime-Iso-In-CustomFields
        in: header
        description: Udfs of DateTime should use Iso
        type: string
        default: 'true'
      - name: EnvApi-Udf-DateTime-ReadInUserTz
        in: header
        description: (obsolete) Udfs of DateTime type whould be in ReadInUserTz
        type: string
      - name: EnvApi-Udf-Value-Invariant
        in: header
        description: (optional) Udfs - Force Non-Localized (invariant) values
        type: string
      - name: EnvApi-Localization-All
        in: header
        description: (optional) Extend objects with User-given Localizations
        type: string
      - name: x-client-request-id
        in: header
        description: (optional) Client ID for double submit prevention
        type: string
      - name: activityIdOrNameOrUniqueTag
        in: path
        required: true
        type: string
      - name: completeBegin
        in: path
        required: true
        type: string
      - name: completeEnd
        in: path
        required: true
        type: string
      - name: locationIdOrPathOrUniqueTag
        in: path
        required: true
        type: string
      responses:
        default:
          description: not available
          schema:
            type: array
            items:
              $ref: '#/definitions/Enviance.RestServices.Ver2.MaterialActivity.Data.MaterialDataLineGroupInfo'
  /ver2/MaterialDataService.svc/materialdata/deletedatacommands/{locationIdOrPathOrUniqueTag}:
    post:
      tags:
      - MaterialData
      description: "\n\n\nenvianceSdk.materialData.deleteMaterialData\r\n```\r\n[\r\n  \"/Division for MDLG/FAC for MDLG\",\r\n  [\r\n    \"6B6BB16B-C207-416C-B818-1DB075AA453C\",\r\n    \"004D8F0D-C03A-4A65-BFD1-3CFFDDF99569\"\r\n  ],\r\n  \"true\",\r\n  \"onsuccess\",\r\n  \"onerror\"\r\n]\r\n```\r\n\n"
      operationId: Enviance.RestServices.Ver2.MaterialActivity.Data.Impl.MaterialDataService.DeleteMaterialData
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: EnvApi-Systemid
        in: header
        description: Specify specific system to run instead of Home
        type: string
      - name: EnvApi-Packageid
        in: header
        description: (optional) Clients application/package ID
        type: string
      - name: EnvApi-Udf-DateTime-Iso-In-CustomFields
        in: header
        description: Udfs of DateTime should use Iso
        type: string
        default: 'true'
      - name: EnvApi-Udf-DateTime-ReadInUserTz
        in: header
        description: (obsolete) Udfs of DateTime type whould be in ReadInUserTz
        type: string
      - name: EnvApi-Udf-Value-Invariant
        in: header
        description: (optional) Udfs - Force Non-Localized (invariant) values
        type: string
      - name: EnvApi-Localization-All
        in: header
        description: (optional) Extend objects with User-given Localizations
        type: string
      - name: x-client-request-id
        in: header
        description: (optional) Client ID for double submit prevention
        type: string
      - name: locationIdOrPathOrUniqueTag
        in: path
        required: true
        type: string
      - name: DeleteMaterialDataWrapper
        in: body
        required: true
        schema:
          $ref: '#/definitions/DeleteMaterialData'
      responses:
        default:
          description: not available
          schema:
            type: string
            format: guid
  /ver2/MaterialDataService.svc/materialdata/download:
    post:
      tags:
      - MaterialData
      description: "\n\n\nenvianceSdk.materialData.downloadMaterialData\r\n```\r\n[\r\n  {\r\n    \"activityIdOrNameOrUniqueTag\": \"Activity for MDLG\",\r\n    \"completeBegin\": \"2015-05-29T00:00:00\",\r\n    \"completeEnd\": \"2015-05-29T00:00:00\",\r\n    \"objectIdOrPathOrUniqueTag\": \"/Division for MDLG/FAC for MDLG\"\r\n  },\r\n  \"onsuccess\",\r\n  \"onerror\"\r\n]\r\n```\r\n\n"
      operationId: Enviance.RestServices.Ver2.MaterialActivity.Data.Impl.MaterialDataService.DownloadMaterialData
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: EnvApi-Systemid
        in: header
        description: Specify specific system to run instead of Home
        type: string
      - name: EnvApi-Packageid
        in: header
        description: (optional) Clients application/package ID
        type: string
      - name: EnvApi-Udf-DateTime-Iso-In-CustomFields
        in: header
        description: Udfs of DateTime should use Iso
        type: string
        default: 'true'
      - name: EnvApi-Udf-DateTime-ReadInUserTz
        in: header
        description: (obsolete) Udfs of DateTime type whould be in ReadInUserTz
        type: string
      - name: EnvApi-Udf-Value-Invariant
        in: header
        description: (optional) Udfs - Force Non-Localized (invariant) values
        type: string
      - name: EnvApi-Localization-All
        in: header
        description: (optional) Extend objects with User-given Localizations
        type: string
      - name: x-client-request-id
        in: header
        description: (optional) Client ID for double submit prevention
        type: string
      - name: DownloadMaterialDataWrapper
        in: body
        required: true
        schema:
          $ref: '#/definitions/DownloadMaterialData'
      responses:
        default:
          description: not available
          schema:
            type: array
            items:
              type: string
              format: byte
  /ver2/MaterialDataService.svc/materialdata/enterdatacommands/:
    post:
      tags:
      - MaterialData
      description: "\n\n\nenvianceSdk.materialData.enterMaterialData\r\n```\r\n[\r\n  [\r\n    {\r\n      \"parentIdOrPathOrUniqueTag\": \"/Division for MDLG/FAC for MDLG\",\r\n      \"activityIdOrNameOrUniqueTag\": \"Activity for MDLG\",\r\n      \"complete\": \"2015-05-29T00:00:00\",\r\n      \"collector\": \"Create MdlG-Happy path\",\r\n      \"dataLines\": [\r\n        {\r\n          \"materialIdOrNameOrUniqueTag\": \"Material 1 for MDLG\",\r\n          \"startTime\": \"2015-05-27T00:00:00\",\r\n          \"endTime\": \"2015-05-28T00:00:00\",\r\n          \"data\": [\r\n            {\r\n              \"propertyIdOrNameOrUniqueTag\": \"SUV10\",\r\n              \"value\": \"1\"\r\n            },\r\n            {\r\n              \"propertyIdOrNameOrUniqueTag\": \"SUV11\",\r\n              \"value\": \"2\"\r\n            }\r\n          ]\r\n        }\r\n      ]\r\n    }\r\n  ],\r\n  true,\r\n  \"onsuccess\",\r\n  \"onerror\"\r\n]\r\n```\r\n\n"
      operationId: Enviance.RestServices.Ver2.MaterialActivity.Data.Impl.MaterialDataService.EnterMaterialData
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: EnvApi-Systemid
        in: header
        description: Specify specific system to run instead of Home
        type: string
      - name: EnvApi-Packageid
        in: header
        description: (optional) Clients application/package ID
        type: string
      - name: EnvApi-Udf-DateTime-Iso-In-CustomFields
        in: header
        description: Udfs of DateTime should use Iso
        type: string
        default: 'true'
      - name: EnvApi-Udf-DateTime-ReadInUserTz
        in: header
        description: (obsolete) Udfs of DateTime type whould be in ReadInUserTz
        type: string
      - name: EnvApi-Udf-Value-Invariant
        in: header
        description: (optional) Udfs - Force Non-Localized (invariant) values
        type: string
      - name: EnvApi-Localization-All
        in: header
        description: (optional) Extend objects with User-given Localizations
        type: string
      - name: x-client-request-id
        in: header
        description: (optional) Client ID for double submit prevention
        type: string
      - name: EnterMaterialDataWrapper
        in: body
        required: true
        schema:
          $ref: '#/definitions/EnterMaterialData'
      responses:
        default:
          description: not available
          schema:
            type: string
            format: guid
  /ver2/MaterialDataService.svc/materialdata/upload:
    post:
      tags:
      - MaterialData
      description: '



        Upload excel template with Ajax and Base64 Encoding. First parameter pass HttpFileInput html control or filecontent as Base64 encoded string. Use anyone (just one) input control on Rest API Test Tool to specify .xls-file to upload file and specify it

        '
      operationId: Enviance.RestServices.Ver2.MaterialActivity.Data.Impl.MaterialDataService.UploadMaterialData
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: EnvApi-Systemid
        in: header
        description: Specify specific system to run instead of Home
        type: string
      - name: EnvApi-Packageid
        in: header
        description: (optional) Clients application/package ID
        type: string
      - name: EnvApi-Udf-DateTime-Iso-In-CustomFields
        in: header
        description: Udfs of DateTime should use Iso
        type: string
        default: 'true'
      - name: EnvApi-Udf-DateTime-ReadInUserTz
        in: header
        description: (obsolete) Udfs of DateTime type whould be in ReadInUserTz
        type: string
      - name: EnvApi-Udf-Value-Invariant
        in: header
        description: (optional) Udfs - Force Non-Localized (invariant) values
        type: string
      - name: EnvApi-Localization-All
        in: header
        description: (optional) Extend objects with User-given Localizations
        type: string
      - name: x-client-request-id
        in: header
        description: (optional) Client ID for double submit prevention
        type: string
      - name: UploadMaterialDataWrapper
        in: body
        required: true
        schema:
          $ref: '#/definitions/UploadMaterialData'
      responses:
        default:
          description: not available
          schema:
            type: string
            format: guid
definitions:
  EnterMaterialData:
    properties:
      mdlGroupsInfo:
        type: array
        items:
          $ref: '#/definitions/Enviance.RestServices.Ver2.MaterialActivity.Data.MaterialDataLineGroupInfo'
        uniqueItems: false
      partialProcess:
        type: string
        uniqueItems: false
    type: object
    format: EnterMaterialData
  Enviance.RestServices.Ver2.MaterialActivity.Data.MaterialDataLineGroupInfo:
    required:
    - complete
    properties:
      id:
        type: string
        format: guid
        uniqueItems: false
      parentIdOrPathOrUniqueTag:
        type: string
        uniqueItems: false
      activityIdOrNameOrUniqueTag:
        type: string
        uniqueItems: false
      complete:
        type: string
        format: date-time
        uniqueItems: false
      collector:
        type: string
        uniqueItems: false
      dataLines:
        type: array
        items:
          $ref: '#/definitions/Enviance.RestServices.Ver2.MaterialActivity.Data.MaterialDataLinesInfo'
        uniqueItems: false
    type: object
    format: Enviance.RestServices.Ver2.MaterialActivity.Data.MaterialDataLineGroupInfo
  DownloadMaterialData:
    properties:
      activityIdOrNameOrUniqueTag:
        type: string
        uniqueItems: false
      completeBegin:
        type: string
        uniqueItems: false
      completeEnd:
        type: string
        uniqueItems: false
      objectIdOrPathOrUniqueTag:
        type: string
        uniqueItems: false
    type: object
    format: DownloadMaterialData
  Enviance.RestServices.Ver2.MaterialActivity.Data.MaterialDataLinesInfo:
    properties:
      materialIdOrNameOrUniqueTag:
        type: string
        uniqueItems: false
      mdlGroupId:
        type: string
        format: guid
        uniqueItems: false
      startTime:
        type: string
        format: date-time
        uniqueItems: false
      endTime:
        type: string
        format: date-time
        uniqueItems: false
      data:
        type: array
        items:
          $ref: '#/definitions/Enviance.RestServices.Ver2.MaterialActivity.Data.MaterialDataInfo'
        uniqueItems: false
    type: object
    format: Enviance.RestServices.Ver2.MaterialActivity.Data.MaterialDataLinesInfo
  UploadMaterialData:
    properties:
      objectIdOrPathOrUniqueTag:
        type: string
        uniqueItems: false
    type: object
    format: UploadMaterialData
  Enviance.RestServices.Ver2.MaterialActivity.Data.MaterialDataInfo:
    properties:
      dataLineId:
        type: string
        format: guid
        uniqueItems: false
      propertyIdOrNameOrUniqueTag:
        type: string
        uniqueItems: false
      value:
        type: number
        format: double
        uniqueItems: false
    type: object
    format: Enviance.RestServices.Ver2.MaterialActivity.Data.MaterialDataInfo
  DeleteMaterialData:
    properties:
      mdlGroupIds:
        type: array
        items:
          type: string
          format: guid
        uniqueItems: false
    type: object
    format: DeleteMaterialData
securityDefinitions:
  Basic:
    type: basic
    description: Forces authentication with credentials via an api gateway
  EnvianceAuth:
    type: apiKey
    description: "**Enviance \\<SessionId\\>**. \r\n\t\t\t\t\t  Obtain SessionId by POST /ver2/AuthenticationService.svc/sessions first"
    name: Authorization
    in: header
