openapi: 3.2.0
info:
  version: Platform.v2026.2.0.0.20260708
  title: Rest Material Property API
  description: EMS Rest API
  contact:
    name: Cority
    email: support@cority.com
    url: https://cority.com
tags:
- name: MaterialProperty
paths:
  /ver2/MaterialPropertyService.svc/materialProperties:
    post:
      tags:
      - MaterialProperty
      description: 'envianceSdk.materialProperties.createMaterialProperty

        ```

        [

        {

        "name": "PFBP Property Name",

        "description": "VBP Description",

        "propertyType": "Formula Based Primary",

        "dataType": "Numeric",

        "formulaHistory": [

        {

        "beginDate": "2012-01-01T20:00:00",

        "Script": "1 \u002B SUM([Chem_MW])"

        },

        {

        "beginDate": "2013-01-01T20:00:00",

        "Script": "1 \u002B [Prop_PFBP1]"

        }

        ]

        },

        "onsuccess",

        "onerror"

        ]

        ```'
      operationId: Enviance.RestServices.Ver2.MaterialActivity.MaterialProperties.Impl.MaterialPropertyService.CreateMaterialProperty
      parameters:
      - name: EnvApi-Systemid
        in: header
        description: Specify specific system to run instead of Home
        schema:
          type: string
      - name: EnvApi-Packageid
        in: header
        description: (optional) Clients application/package ID
        schema:
          type: string
      - name: EnvApi-Udf-DateTime-Iso-In-CustomFields
        in: header
        description: Udfs of DateTime should use Iso
        schema:
          type: string
          default: 'true'
      - name: EnvApi-Udf-DateTime-ReadInUserTz
        in: header
        description: (obsolete) Udfs of DateTime type whould be in ReadInUserTz
        schema:
          type: string
      - name: EnvApi-Udf-Value-Invariant
        in: header
        description: (optional) Udfs - Force Non-Localized (invariant) values
        schema:
          type: string
      - name: EnvApi-Localization-All
        in: header
        description: (optional) Extend objects with User-given Localizations
        schema:
          type: string
      - name: x-client-request-id
        in: header
        description: (optional) Client ID for double submit prevention
        schema:
          type: string
      responses:
        default:
          description: not available
          content:
            application/json:
              schema:
                type: string
                format: guid
            application/xml:
              schema:
                type: string
                format: guid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMaterialProperty'
          application/xml:
            schema:
              $ref: '#/components/schemas/CreateMaterialProperty'
        required: true
      summary: Enviance rest services ver2 material activity material properties impl material…
      x-summary-source: derived
  /ver2/MaterialPropertyService.svc/materialProperties/{materialPropertyIdOrName}:
    get:
      tags:
      - MaterialProperty
      description: 'envianceSdk.materialProperties.getMaterialProperty

        ```

        [

        "Material Property Name",

        "onsuccess",

        "onerror"

        ]

        ```'
      operationId: Enviance.RestServices.Ver2.MaterialActivity.MaterialProperties.Impl.MaterialPropertyService.GetMaterialProperty
      parameters:
      - name: EnvApi-Systemid
        in: header
        description: Specify specific system to run instead of Home
        schema:
          type: string
      - name: EnvApi-Packageid
        in: header
        description: (optional) Clients application/package ID
        schema:
          type: string
      - name: EnvApi-Udf-DateTime-Iso-In-CustomFields
        in: header
        description: Udfs of DateTime should use Iso
        schema:
          type: string
          default: 'true'
      - name: EnvApi-Udf-DateTime-ReadInUserTz
        in: header
        description: (obsolete) Udfs of DateTime type whould be in ReadInUserTz
        schema:
          type: string
      - name: EnvApi-Udf-Value-Invariant
        in: header
        description: (optional) Udfs - Force Non-Localized (invariant) values
        schema:
          type: string
      - name: EnvApi-Localization-All
        in: header
        description: (optional) Extend objects with User-given Localizations
        schema:
          type: string
      - name: x-client-request-id
        in: header
        description: (optional) Client ID for double submit prevention
        schema:
          type: string
      - name: materialPropertyIdOrName
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: not available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Enviance.RestServices.Ver2.MaterialActivity.MaterialProperties.MaterialPropertyInfo'
            application/xml:
              schema:
                $ref: '#/components/schemas/Enviance.RestServices.Ver2.MaterialActivity.MaterialProperties.MaterialPropertyInfo'
      summary: Enviance rest services ver2 material activity material properties impl material…
      x-summary-source: derived
    patch:
      tags:
      - MaterialProperty
      description: 'envianceSdk.materialProperties.updateMaterialProperty

        ```

        [

        "Material Property Name",

        {

        "name": "PFBP Property Name",

        "description": "VBP Description",

        "dataType": "Numeric",

        "formulaHistory": [

        {

        "beginDate": "2012-01-01T20:00:00",

        "Script": "1 \u002B SUM([Chem_MW])"

        },

        {

        "beginDate": "2013-01-01T20:00:00",

        "Script": "1 \u002B [Prop_PFBP1]"

        }

        ]

        },

        "onsuccess",

        "onerror"

        ]

        ```'
      operationId: Enviance.RestServices.Ver2.MaterialActivity.MaterialProperties.Impl.MaterialPropertyService.UpdateMaterialProperty
      parameters:
      - name: EnvApi-Systemid
        in: header
        description: Specify specific system to run instead of Home
        schema:
          type: string
      - name: EnvApi-Packageid
        in: header
        description: (optional) Clients application/package ID
        schema:
          type: string
      - name: EnvApi-Udf-DateTime-Iso-In-CustomFields
        in: header
        description: Udfs of DateTime should use Iso
        schema:
          type: string
          default: 'true'
      - name: EnvApi-Udf-DateTime-ReadInUserTz
        in: header
        description: (obsolete) Udfs of DateTime type whould be in ReadInUserTz
        schema:
          type: string
      - name: EnvApi-Udf-Value-Invariant
        in: header
        description: (optional) Udfs - Force Non-Localized (invariant) values
        schema:
          type: string
      - name: EnvApi-Localization-All
        in: header
        description: (optional) Extend objects with User-given Localizations
        schema:
          type: string
      - name: x-client-request-id
        in: header
        description: (optional) Client ID for double submit prevention
        schema:
          type: string
      - name: materialPropertyIdOrName
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: not available
          content:
            application/json:
              schema:
                type: string
                format: guid
            application/xml:
              schema:
                type: string
                format: guid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMaterialProperty'
          application/xml:
            schema:
              $ref: '#/components/schemas/UpdateMaterialProperty'
        required: true
      summary: Enviance rest services ver2 material activity material properties impl material…
      x-summary-source: derived
    delete:
      tags:
      - MaterialProperty
      description: 'envianceSdk.materialProperties.deleteMaterialProperty

        ```

        [

        "Material Property Name",

        "onsuccess",

        "onerror"

        ]

        ```'
      operationId: Enviance.RestServices.Ver2.MaterialActivity.MaterialProperties.Impl.MaterialPropertyService.DeleteMaterialProperty
      parameters:
      - name: EnvApi-Systemid
        in: header
        description: Specify specific system to run instead of Home
        schema:
          type: string
      - name: EnvApi-Packageid
        in: header
        description: (optional) Clients application/package ID
        schema:
          type: string
      - name: EnvApi-Udf-DateTime-Iso-In-CustomFields
        in: header
        description: Udfs of DateTime should use Iso
        schema:
          type: string
          default: 'true'
      - name: EnvApi-Udf-DateTime-ReadInUserTz
        in: header
        description: (obsolete) Udfs of DateTime type whould be in ReadInUserTz
        schema:
          type: string
      - name: EnvApi-Udf-Value-Invariant
        in: header
        description: (optional) Udfs - Force Non-Localized (invariant) values
        schema:
          type: string
      - name: EnvApi-Localization-All
        in: header
        description: (optional) Extend objects with User-given Localizations
        schema:
          type: string
      - name: x-client-request-id
        in: header
        description: (optional) Client ID for double submit prevention
        schema:
          type: string
      - name: materialPropertyIdOrName
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: not available
      summary: Enviance rest services ver2 material activity material properties impl material…
      x-summary-source: derived
components:
  schemas:
    CreateMaterialProperty:
      properties:
        materialPropertyInfo:
          $ref: '#/components/schemas/Enviance.RestServices.Ver2.MaterialActivity.MaterialProperties.MaterialPropertyInfo'
        copyFrom:
          type: string
          uniqueItems: false
      type: object
      format: CreateMaterialProperty
    UpdateMaterialProperty:
      properties:
        materialPropertyInfo:
          $ref: '#/components/schemas/Enviance.RestServices.Ver2.MaterialActivity.MaterialProperties.MaterialPropertyInfo'
      type: object
      format: UpdateMaterialProperty
    Enviance.RestServices.Ver2.MaterialActivity.MaterialProperties.MaterialPropertyInfo:
      properties:
        id:
          type: string
          format: guid
          uniqueItems: false
        name:
          type: string
          uniqueItems: false
        propertyType:
          type: string
          uniqueItems: false
        description:
          type: string
          uniqueItems: false
        dataType:
          type: string
          uniqueItems: false
        uniqueTag:
          type: string
          uniqueItems: false
        formulaHistory:
          type: array
          items:
            $ref: '#/components/schemas/Enviance.RestServices.Ver2.MaterialActivity.MaterialProperties.FormulaHistoryInfo'
          uniqueItems: false
      type: object
      format: Enviance.RestServices.Ver2.MaterialActivity.MaterialProperties.MaterialPropertyInfo
    Enviance.RestServices.Ver2.MaterialActivity.MaterialProperties.FormulaHistoryInfo:
      properties:
        id:
          type: string
          format: guid
          uniqueItems: false
        beginDate:
          type: string
          format: date-time
          uniqueItems: false
        script:
          type: string
          uniqueItems: false
      type: object
      format: Enviance.RestServices.Ver2.MaterialActivity.MaterialProperties.FormulaHistoryInfo
  securitySchemes:
    Basic:
      type: http
      scheme: basic
      description: Forces authentication with credentials via an api gateway
    EnvianceAuth:
      type: apiKey
      description: "**Enviance \\<SessionId\\>**. \n\t\t\t\t\t  Obtain SessionId by POST /ver2/AuthenticationService.svc/sessions first"
      name: Authorization
      in: header
