swagger: '2.0'
info:
  version: Platform.v2026.2.0.0.20260708
  title: Rest Activity ChemicalList API
  description: EMS Rest API
  contact:
    name: Cority
    email: support@cority.com
    url: https://cority.com
tags:
- name: ChemicalList
paths:
  /ver2/ChemicalListService.svc/chemicalLists:
    post:
      tags:
      - ChemicalList
      description: "\n\n\nenvianceSdk.chemicallists.createChemicalList\r\n```\r\n[\r\n  {\r\n    \"name\": \"Chemical List Name\",\r\n    \"description\": \"Chemical List Description\",\r\n    \"chemicalListHistoryItems\": [\r\n      {\r\n        \"beginDate\": \"2012-01-01T20:00:00\",\r\n        \"limits\": [\r\n          {\r\n            \"chemicalIdOrAlias\": \"FF710D9F-4367-4C0C-A5CB-497CB18FA842\",\r\n            \"limit\": \"1\"\r\n          },\r\n          {\r\n            \"chemicalIdOrAlias\": \"5376DF01-45B5-4153-ACCF-8E208DB69979\",\r\n            \"limit\": \"1\"\r\n          }\r\n        ]\r\n      },\r\n      {\r\n        \"beginDate\": \"2013-01-01T20:00:00\",\r\n        \"limits\": [\r\n          {\r\n            \"chemicalIdOrAlias\": \"FF710D9F-4367-4C0C-A5CB-497CB18FA842\",\r\n            \"limit\": \"3\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  },\r\n  \"onsuccess\",\r\n  \"onerror\"\r\n]\r\n```\r\n\n"
      operationId: Enviance.RestServices.Ver2.MaterialActivity.Chemicals.Impl.ChemicalListService.CreateChemicalList
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: EnvApi-Systemid
        in: header
        description: Specify specific system to run instead of Home
        type: string
      - name: EnvApi-Packageid
        in: header
        description: (optional) Clients application/package ID
        type: string
      - name: EnvApi-Udf-DateTime-Iso-In-CustomFields
        in: header
        description: Udfs of DateTime should use Iso
        type: string
        default: 'true'
      - name: EnvApi-Udf-DateTime-ReadInUserTz
        in: header
        description: (obsolete) Udfs of DateTime type whould be in ReadInUserTz
        type: string
      - name: EnvApi-Udf-Value-Invariant
        in: header
        description: (optional) Udfs - Force Non-Localized (invariant) values
        type: string
      - name: EnvApi-Localization-All
        in: header
        description: (optional) Extend objects with User-given Localizations
        type: string
      - name: x-client-request-id
        in: header
        description: (optional) Client ID for double submit prevention
        type: string
      - name: CreateChemicalListWrapper
        in: body
        required: true
        schema:
          $ref: '#/definitions/CreateChemicalList'
      responses:
        default:
          description: not available
          schema:
            type: string
            format: guid
  /ver2/ChemicalListService.svc/chemicalLists/{chemicalListIdOrName}:
    patch:
      tags:
      - ChemicalList
      description: "\n\n\nenvianceSdk.chemicallists.updateChemicalList\r\n```\r\n[\r\n  \"Chemical List Name\",\r\n  {\r\n    \"name\": \"Chemical List Name\",\r\n    \"description\": \"Chemical List Description\",\r\n    \"chemicalListHistoryItems\": [\r\n      {\r\n        \"beginDate\": \"2012-01-01T20:00:00\",\r\n        \"limits\": [\r\n          {\r\n            \"chemicalIdOrAlias\": \"FF710D9F-4367-4C0C-A5CB-497CB18FA842\",\r\n            \"limit\": \"1\"\r\n          },\r\n          {\r\n            \"chemicalIdOrAlias\": \"5376DF01-45B5-4153-ACCF-8E208DB69979\",\r\n            \"limit\": \"1\"\r\n          }\r\n        ]\r\n      },\r\n      {\r\n        \"beginDate\": \"2013-01-01T20:00:00\",\r\n        \"limits\": [\r\n          {\r\n            \"chemicalIdOrAlias\": \"FF710D9F-4367-4C0C-A5CB-497CB18FA842\",\r\n            \"limit\": \"3\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  },\r\n  \"onsuccess\",\r\n  \"onerror\"\r\n]\r\n```\r\n\n"
      operationId: Enviance.RestServices.Ver2.MaterialActivity.Chemicals.Impl.ChemicalListService.UpdateChemicalList
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: EnvApi-Systemid
        in: header
        description: Specify specific system to run instead of Home
        type: string
      - name: EnvApi-Packageid
        in: header
        description: (optional) Clients application/package ID
        type: string
      - name: EnvApi-Udf-DateTime-Iso-In-CustomFields
        in: header
        description: Udfs of DateTime should use Iso
        type: string
        default: 'true'
      - name: EnvApi-Udf-DateTime-ReadInUserTz
        in: header
        description: (obsolete) Udfs of DateTime type whould be in ReadInUserTz
        type: string
      - name: EnvApi-Udf-Value-Invariant
        in: header
        description: (optional) Udfs - Force Non-Localized (invariant) values
        type: string
      - name: EnvApi-Localization-All
        in: header
        description: (optional) Extend objects with User-given Localizations
        type: string
      - name: x-client-request-id
        in: header
        description: (optional) Client ID for double submit prevention
        type: string
      - name: chemicalListIdOrName
        in: path
        required: true
        type: string
      - name: UpdateChemicalListWrapper
        in: body
        required: true
        schema:
          $ref: '#/definitions/UpdateChemicalList'
      responses:
        default:
          description: not available
          schema:
            type: string
            format: guid
    delete:
      tags:
      - ChemicalList
      description: "\n\n\nenvianceSdk.chemicallists.deleteChemicalList\r\n```\r\n[\r\n  \"Chemical List Name\",\r\n  \"onsuccess\",\r\n  \"onerror\"\r\n]\r\n```\r\n\n"
      operationId: Enviance.RestServices.Ver2.MaterialActivity.Chemicals.Impl.ChemicalListService.DeleteChemicalList
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: EnvApi-Systemid
        in: header
        description: Specify specific system to run instead of Home
        type: string
      - name: EnvApi-Packageid
        in: header
        description: (optional) Clients application/package ID
        type: string
      - name: EnvApi-Udf-DateTime-Iso-In-CustomFields
        in: header
        description: Udfs of DateTime should use Iso
        type: string
        default: 'true'
      - name: EnvApi-Udf-DateTime-ReadInUserTz
        in: header
        description: (obsolete) Udfs of DateTime type whould be in ReadInUserTz
        type: string
      - name: EnvApi-Udf-Value-Invariant
        in: header
        description: (optional) Udfs - Force Non-Localized (invariant) values
        type: string
      - name: EnvApi-Localization-All
        in: header
        description: (optional) Extend objects with User-given Localizations
        type: string
      - name: x-client-request-id
        in: header
        description: (optional) Client ID for double submit prevention
        type: string
      - name: chemicalListIdOrName
        in: path
        required: true
        type: string
      responses:
        default:
          description: not available
  /ver2/ChemicalListService.svc/ChemicalLists/{chemicalListIdOrName}:
    get:
      tags:
      - ChemicalList
      description: "\n\n\nenvianceSdk.chemicallists.getChemicalList\r\n```\r\n[\r\n  \"Chemical List Name\",\r\n  \"onsuccess\",\r\n  \"onerror\"\r\n]\r\n```\r\n\n"
      operationId: Enviance.RestServices.Ver2.MaterialActivity.Chemicals.Impl.ChemicalListService.GetChemicalList
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: EnvApi-Systemid
        in: header
        description: Specify specific system to run instead of Home
        type: string
      - name: EnvApi-Packageid
        in: header
        description: (optional) Clients application/package ID
        type: string
      - name: EnvApi-Udf-DateTime-Iso-In-CustomFields
        in: header
        description: Udfs of DateTime should use Iso
        type: string
        default: 'true'
      - name: EnvApi-Udf-DateTime-ReadInUserTz
        in: header
        description: (obsolete) Udfs of DateTime type whould be in ReadInUserTz
        type: string
      - name: EnvApi-Udf-Value-Invariant
        in: header
        description: (optional) Udfs - Force Non-Localized (invariant) values
        type: string
      - name: EnvApi-Localization-All
        in: header
        description: (optional) Extend objects with User-given Localizations
        type: string
      - name: x-client-request-id
        in: header
        description: (optional) Client ID for double submit prevention
        type: string
      - name: chemicalListIdOrName
        in: path
        required: true
        type: string
      responses:
        default:
          description: not available
          schema:
            $ref: '#/definitions/Enviance.RestServices.Ver2.MaterialActivity.Chemicals.ChemicalListInfo'
definitions:
  Enviance.RestServices.Ver2.MaterialActivity.Chemicals.ChemicalListLimitItemInfo:
    properties:
      chemicalIdOrAlias:
        type: string
        uniqueItems: false
      limit:
        type: number
        format: double
        uniqueItems: false
    type: object
    format: Enviance.RestServices.Ver2.MaterialActivity.Chemicals.ChemicalListLimitItemInfo
  CreateChemicalList:
    properties:
      chemicalListInfo:
        $ref: '#/definitions/Enviance.RestServices.Ver2.MaterialActivity.Chemicals.ChemicalListInfo'
      copyFrom:
        type: string
        uniqueItems: false
    type: object
    format: CreateChemicalList
  UpdateChemicalList:
    properties:
      chemicalListInfo:
        $ref: '#/definitions/Enviance.RestServices.Ver2.MaterialActivity.Chemicals.ChemicalListInfo'
    type: object
    format: UpdateChemicalList
  Enviance.RestServices.Ver2.MaterialActivity.Chemicals.ChemicalListInfo:
    properties:
      id:
        type: string
        format: guid
        uniqueItems: false
      name:
        type: string
        uniqueItems: false
      description:
        type: string
        uniqueItems: false
      chemicalListHistoryItems:
        type: array
        items:
          $ref: '#/definitions/Enviance.RestServices.Ver2.MaterialActivity.Chemicals.ChemicalListHistoryItemInfo'
        uniqueItems: false
    type: object
    format: Enviance.RestServices.Ver2.MaterialActivity.Chemicals.ChemicalListInfo
  Enviance.RestServices.Ver2.MaterialActivity.Chemicals.ChemicalListHistoryItemInfo:
    properties:
      id:
        type: string
        format: guid
        uniqueItems: false
      beginDate:
        type: string
        format: date-time
        uniqueItems: false
      limits:
        type: array
        items:
          $ref: '#/definitions/Enviance.RestServices.Ver2.MaterialActivity.Chemicals.ChemicalListLimitItemInfo'
        uniqueItems: false
    type: object
    format: Enviance.RestServices.Ver2.MaterialActivity.Chemicals.ChemicalListHistoryItemInfo
securityDefinitions:
  Basic:
    type: basic
    description: Forces authentication with credentials via an api gateway
  EnvianceAuth:
    type: apiKey
    description: "**Enviance \\<SessionId\\>**. \r\n\t\t\t\t\t  Obtain SessionId by POST /ver2/AuthenticationService.svc/sessions first"
    name: Authorization
    in: header
