openapi: 3.2.0
info:
  version: Platform.v2026.2.0.0.20260708
  title: Rest Main Menu Service API
  description: EMS Rest API
  contact:
    name: Cority
    email: support@cority.com
    url: https://cority.com
tags:
- name: MainMenuService
paths:
  /ver2/MainMenuService.svc/mainMenu:
    get:
      tags:
      - MainMenuService
      operationId: Enviance.RestServices.Ver2.MainMenu.Impl.MainMenuService.GetMainMenu
      parameters:
      - name: EnvApi-Systemid
        in: header
        description: Specify specific system to run instead of Home
        schema:
          type: string
      - name: EnvApi-Packageid
        in: header
        description: (optional) Clients application/package ID
        schema:
          type: string
      - name: EnvApi-Udf-DateTime-Iso-In-CustomFields
        in: header
        description: Udfs of DateTime should use Iso
        schema:
          type: string
          default: 'true'
      - name: EnvApi-Udf-DateTime-ReadInUserTz
        in: header
        description: (obsolete) Udfs of DateTime type whould be in ReadInUserTz
        schema:
          type: string
      - name: EnvApi-Udf-Value-Invariant
        in: header
        description: (optional) Udfs - Force Non-Localized (invariant) values
        schema:
          type: string
      - name: EnvApi-Localization-All
        in: header
        description: (optional) Extend objects with User-given Localizations
        schema:
          type: string
      - name: x-client-request-id
        in: header
        description: (optional) Client ID for double submit prevention
        schema:
          type: string
      responses:
        default:
          description: not available
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Enviance.RestServices.Ver2.MainMenu.MainMenuInfo'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Enviance.RestServices.Ver2.MainMenu.MainMenuInfo'
      summary: Enviance rest services ver2 main menu impl main menu service get main menu
      x-summary-source: derived
components:
  schemas:
    Enviance.RestServices.Ver2.MainMenu.MainMenuInfo:
      properties:
        key:
          type: string
          uniqueItems: false
        title:
          type: string
          uniqueItems: false
        description:
          type: string
          uniqueItems: false
        path:
          type: string
          uniqueItems: false
        urlIframe:
          type: string
          uniqueItems: false
        url:
          type: string
          uniqueItems: false
        urlInternal:
          type: string
          uniqueItems: false
        urlFull:
          type: string
          uniqueItems: false
        iconUrl:
          type: string
          uniqueItems: false
        isStatic:
          type: boolean
          uniqueItems: false
        children:
          type: array
          items:
            $ref: '#/components/schemas/Enviance.RestServices.Ver2.MainMenu.MainMenuInfo'
          uniqueItems: false
      type: object
      format: Enviance.RestServices.Ver2.MainMenu.MainMenuInfo
  securitySchemes:
    Basic:
      type: http
      scheme: basic
      description: Forces authentication with credentials via an api gateway
    EnvianceAuth:
      type: apiKey
      description: "**Enviance \\<SessionId\\>**. \n\t\t\t\t\t  Obtain SessionId by POST /ver2/AuthenticationService.svc/sessions first"
      name: Authorization
      in: header
